service: hvt-svc-authoriser

plugins:
  - serverless-dotenv-plugin
  - serverless-offline

provider:
  region: eu-west-1
  name: aws
  runtime: nodejs24.x
  timeout: 60

functions:
  authoriserFunction:
    handler: authoriser/handler.handler
  testFunction:
    handler: tests/handler.test
    events:
      - http:
          path: testFunction
          method: POST
          authorizer: authoriserFunction
